//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _17599075_PROG_POE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUIZ
    {
        public int ID { get; set; }
        public string QUESTION { get; set; }
        public string SOL_A { get; set; }
        public string SOL_B { get; set; }
        public string SOL_C { get; set; }
        public string CORRECT_ANSWER { get; set; }
    }
}
